import { ChangeDetectionStrategy, Component, computed, input } from '@angular/core';
import { InvestorPosition } from '../../domain/models/position';
import { calculateAverageDown, calculateTargetAverage, calculateAveragingScenarios } from '../../domain/calculations/average-down';
import { MetricPipe } from '../../core/utilities/format';
import { Icon } from '../../shared/components/icon';
@Component({ selector: 'eq-average-down-details', imports: [MetricPipe, Icon], changeDetection: ChangeDetectionStrategy.OnPush,
 template: `@if (result(); as r) {
 <section class="comparison panel supplement"><div class="section-heading"><div><h2>The same position. A different average.</h2><p>Your numbers before and after the additional purchase.</p></div></div><div class="compare-grid"><div class="before"><span class="section-eyebrow">CURRENT POSITION</span><h3>{{ position().averagePrice | metric:'currency' }}<small>Average price</small></h3><dl><div><dt>Shares</dt><dd>{{ position().quantity | metric }}</dd></div><div><dt>Capital invested</dt><dd>{{ r.currentInvestment | metric:'currency' }}</dd></div><div><dt>Current value</dt><dd>{{ r.currentValue | metric:'currency' }}</dd></div><div><dt>Unrealised P&L</dt><dd [class.negative]="r.currentPnl < 0" [class.positive]="r.currentPnl > 0">{{ r.currentPnl | metric:'currency' }}</dd></div><div><dt>Recovery required</dt><dd>{{ r.oldRecoveryPercentage === 0 ? 'Break-even reached' : (r.oldRecoveryPercentage | metric:'percentage') }}</dd></div></dl></div><div class="compare-arrow"><eq-icon name="arrow" /></div><div class="after"><span class="section-eyebrow">AFTER ADDING {{ r.additionalInvestmentUsed | metric:'currency' }}</span><h3>{{ r.newAverage | metric:'currency' }}<small>New average price</small></h3><dl><div><dt>Shares</dt><dd>{{ r.totalQuantity | metric }}</dd></div><div><dt>Capital invested</dt><dd>{{ r.totalInvestment | metric:'currency' }}</dd></div><div><dt>Additional shares</dt><dd>+{{ r.additionalShares | metric }}</dd></div><div><dt>Average {{ r.averageReduction >= 0 ? 'reduced' : 'increased' }} by</dt><dd>{{ absolute(r.averageReduction) | metric:'currency' }}</dd></div><div><dt>Recovery required</dt><dd>{{ r.newRecoveryPercentage === 0 ? 'Break-even reached' : (r.newRecoveryPercentage | metric:'percentage') }}</dd></div></dl></div></div><div class="comparison-insight"><eq-icon name="info" /><p>This adds <strong>{{ r.additionalInvestmentUsed | metric:'currency' }}</strong> of capital. Your existing rupee P&L at this market price is unchanged. @if (mode() === 'target') { Whole shares are rounded up to meet or better your requested average of {{ amount() | metric:'currency' }}. }</p></div></section>
 <section class="panel supplement"><div class="section-heading"><div><h2>What if you invested a little differently?</h2><p>Compare nearby budgets. Every scenario uses whole shares.</p></div></div><div class="table-wrap" tabindex="0" role="region" aria-label="Averaging scenarios"><table><thead><tr><th scope="col">Budget</th><th scope="col">New shares</th><th scope="col">Capital used</th><th scope="col">New average</th><th scope="col">Recovery</th></tr></thead><tbody>@for (s of scenarios(); track s.budget) { <tr [class.highlight]="$index === 2"><td>{{ s.budget | metric:'currency' }}</td><td>{{ s.additionalShares | metric }}</td><td>{{ s.additionalInvestmentUsed | metric:'currency' }}</td><td>{{ s.newAverage | metric:'currency' }}</td><td>{{ s.newRecoveryPercentage === 0 ? 'Reached' : (s.newRecoveryPercentage | metric:'percentage') }}</td></tr> }</tbody></table></div><p class="scenario-note">Illustrations of additional exposure, not suggestions to invest. Unused budget stays outside the position.</p></section>
 }`,
 styles: `.compare-grid { display: grid; grid-template-columns: minmax(0, 1fr) 38px minmax(0, 1fr); align-items: center; }.before,.after { padding: 22px; border: 1px solid var(--eq-border); border-radius: 8px; min-width: 0; }.after { background: var(--eq-brand-soft); }.compare-grid .section-eyebrow { font-size: 8px; line-height: 1.6; }.compare-grid h3 { font-size: 29px; letter-spacing: -.8px; margin: 17px 0; overflow-wrap: anywhere; font-variant-numeric: tabular-nums; }.after h3 { color: var(--eq-brand); }.compare-grid small { display: block; font-size: 10px; font-weight: 400; color: var(--eq-text-muted); letter-spacing: 0; margin-top: 4px; }.compare-grid dl { margin: 0; }.compare-grid dl>div { display: flex; gap: 12px; justify-content: space-between; font-size: 11px; margin-top: 14px; }.compare-grid dt { color: var(--eq-text-secondary); }.compare-grid dd { margin: 0; text-align: right; font-weight: 550; overflow-wrap: anywhere; min-width: 0; }.compare-arrow { display: flex; justify-content: center; color: var(--eq-brand); }.comparison-insight { display: flex; gap: 9px; margin-top: 19px; align-items: flex-start; }.comparison-insight eq-icon { width: 15px; height: 15px; color: var(--eq-brand); margin-top: 2px; }.comparison-insight p,.scenario-note { margin: 0; font-size: 11px; line-height: 1.8; }.scenario-note { margin-top: 16px; color: var(--eq-text-muted); }@media(max-width: 600px) { .compare-grid { grid-template-columns: 1fr; gap: 12px; }.compare-arrow { transform: rotate(90deg); }.before,.after { padding: 18px; }.comparison h2 { font-size: 17px; } }`
})
export class AverageDownDetails {
 readonly position = input.required<InvestorPosition>(); readonly amount = input.required<number>(); readonly mode = input('investment'); readonly absolute = Math.abs;
 readonly result = computed(() => { try { return this.mode() === 'target' ? calculateTargetAverage(this.position(), this.amount()) : calculateAverageDown(this.position(), this.amount()); } catch { return null; } });
 readonly scenarios = computed(() => { const r = this.result(); if (!r) return []; const budget = this.mode() === 'target' ? r.additionalInvestmentUsed : this.amount(); try { return calculateAveragingScenarios(this.position(), Math.max(budget, this.position().currentPrice)); } catch { return []; } });
}
