import { ChangeDetectionStrategy, Component, inject, signal } from '@angular/core';
import { ThemeStore, Theme } from '../../core/state/theme';
import { PreferencesStore } from '../../core/state/preferences';
import { HistoryStore } from '../../core/state/history';
import { SavedStore } from '../../core/state/saved';
import { FavouritesStore } from '../../core/state/favourites';
import { RecentStore } from '../../core/state/recent';
import { PositionStore } from '../../core/state/position';
import { StorageService } from '../../core/storage/storage';
@Component({ selector: 'eq-settings', changeDetection: ChangeDetectionStrategy.OnPush,
 template: `<header class="page-header"><div class="eyebrow">MAKE YOURSELF AT HOME</div><h1>Your workspace. Your preferences.</h1><p>Choose how EquiCalc looks and what it remembers in this browser.</p></header><section class="panel settings-panel"><h2>Appearance & numbers</h2><div class="setting-row"><div><h3>Theme</h3><p>Follow your system or choose an appearance.</p></div><div class="segmented" aria-label="Theme preference">@for (option of themes; track option) { <button [class.active]="theme.preference() === option" [attr.aria-pressed]="theme.preference() === option" (click)="theme.set(option)">{{ option }}</button> }</div></div><div class="setting-row"><div><h3>Compact currency display</h3><p>Use K, L and Cr for larger amounts. Calculations retain full precision.</p></div><label class="toggle"><input type="checkbox" #compactToggle [checked]="preferences.compact()" (change)="preferences.setCompact(compactToggle.checked)" aria-label="Compact currency display" /><span aria-hidden="true"></span></label></div><div class="number-example">Example <strong>{{ preferences.compact() ? '₹25L' : '₹25,00,000.00' }}</strong><span>INR · Indian digit grouping</span></div></section><section class="panel settings-panel"><h2>Local data</h2><div class="setting-row"><div><h3>Calculation history</h3><p>Remember complete calculations after you pause typing. Up to 100 entries.</p></div><label class="toggle"><input #historyToggle type="checkbox" [checked]="preferences.historyEnabled()" (change)="preferences.setHistory(historyToggle.checked)" aria-label="Enable calculation history" /><span aria-hidden="true"></span></label></div><div class="setting-row"><div><h3>Clear history</h3><p>{{ history.items().length }} calculations in this browser.</p></div><button class="btn danger" (click)="clear('history')" [disabled]="!history.items().length">Clear history</button></div><div class="setting-row"><div><h3>Clear saved calculations</h3><p>{{ saved.items().length }} saved scenarios. This cannot be undone.</p></div><button class="btn danger" (click)="clear('saved')" [disabled]="!saved.items().length">Clear saved</button></div><div class="setting-row"><div><h3>Clear all local EquiCalc data</h3><p>Remove saved calculations, history, position, favourites and preferences.</p></div><button class="btn danger" (click)="clear('all')">Clear all data</button></div></section><p class="notice">EquiCalc has no account or cloud sync. Clearing browser site data also removes your saved calculations.</p>@if (message()) { <p class="status-message" role="status">{{ message() }}</p> }`,
 styles: `.settings-panel { max-width: 900px; margin-bottom: 22px; }.settings-panel>h2 { font-size: 16px; margin-bottom: 10px; }.setting-row { display: flex; justify-content: space-between; align-items: center; gap: 26px; padding: 25px 0; border-bottom: 1px solid var(--eq-border); }.setting-row:last-child { border: 0; padding-bottom: 5px; }.setting-row h3 { font-size: 13px; margin: 0 0 5px; }.setting-row p { font-size: 11px; margin: 0; max-width: 480px; line-height: 1.7; }.setting-row .btn { flex: 0 0 auto; }.segmented { margin: 0; flex-wrap: nowrap; }.segmented button { text-transform: capitalize; }.toggle { position: relative; margin: 0; flex: 0 0 auto; width: 48px; height: 44px; display: grid; place-items: center; }.toggle input { position: absolute; opacity: 0; width: 100%; height: 100%; cursor: pointer; margin: 0; }.toggle span { width: 42px; height: 24px; border-radius: 15px; background: var(--eq-border-strong); pointer-events: none; }.toggle span::after { content: ''; display: block; width: 18px; height: 18px; margin: 3px; background: var(--eq-surface); border-radius: 50%; transition: transform .15s; }.toggle input:checked+span { background: var(--eq-brand); }.toggle input:checked+span::after { transform: translateX(18px); }.toggle input:focus-visible+span { outline: 3px solid var(--eq-brand); outline-offset: 3px; }.number-example { display: flex; gap: 16px; flex-wrap: wrap; margin-top: 20px; color: var(--eq-text-muted); font-size: 11px; }.number-example strong { color: var(--eq-text); }.number-example>span { margin-left: auto; }@media(max-width: 600px) { .setting-row { gap: 15px; flex-wrap: wrap; }.setting-row>div:first-child { flex: 1 1 200px; }.setting-row .segmented { width: 100%; } }`
})
export class Settings {
 readonly theme = inject(ThemeStore); readonly preferences = inject(PreferencesStore); readonly history = inject(HistoryStore); readonly saved = inject(SavedStore);
 private readonly favourites = inject(FavouritesStore); private readonly recent = inject(RecentStore); private readonly position = inject(PositionStore); private readonly storage = inject(StorageService);
 readonly themes: readonly Theme[] = ['light', 'dark', 'system']; readonly message = signal('');
 clear(type: 'all' | 'saved' | 'history'): void {
   if (!confirm(`Clear ${type === 'all' ? 'all local EquiCalc data' : type === 'saved' ? 'all saved calculations' : 'all calculation history'}? This cannot be undone.`)) return;
   if (type === 'history' || type === 'all') this.history.clear();
   if (type === 'saved' || type === 'all') this.saved.clear();
   if (type === 'all') { this.favourites.clear(); this.recent.clear(); this.position.clear(); this.preferences.setCompact(false); this.preferences.setHistory(true); this.theme.set('system'); this.storage.clear(); }
   this.message.set('Local data cleared.');
 }
}
